### ISSUE TITLE
need more function in product entity

### ISSUE THREAD

**Issue by tlan16** [tlan16/sushi-co#10]
add will add single one
remove will remove single one
clear will clear all
get will get all

e.g. addMaterial(Material)
removeMaterial(Material)
clearMaterial()
getMaterials()

need done for Material, Category, store, 

addStore(Store $store, $unitprice = 0)
will create a new product info with defualt value of 0, if special price for this store, setValue to special unitPrice

---

$product->print(.....)
will create a new label for this product, pass in almost same params as Label::create

**Comment by helin16** [comment]
@tlan16 . done
